name: 'Deploy to Cloudflare Pages'

on:
  push:
    branches: ['release']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: 'cf-pages'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    environment:
      name: Production
      url: ${{ steps.publish.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
      - name: build
        run: |
          yarn
          yarn build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        id: publish
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 535c9adaae9f1f866fbf86b609b76f30
          projectName: homepage
          directory: build
          branch: main
