name: 'Deploy to Cloudflare Pages'

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: 'cf-pages'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    environment:
      name: Production
      url: ${{ steps.publish.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
      - name: build
        run: |
          yarn
          yarn build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        id: publish
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 535c9adaae9f1f866fbf86b609b76f30
          projectName: homepage
          directory: build
          branch: main

  next-release-cycle:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Install dependencies
        run: yarn

      - name: Prepare next development cycle
        run: |
          git config --local user.email "github.bot@troublor.xyz"
          git config --local user.name "Troublor Bot"
          yarn version prerelease
          git add package.json
          export next_version=$(jq -r .version package.json)
          git commit -m "chore: prepare next development cycle v$next_version"
          echo "next_version=$next_version" >> $GITHUB_ENV

      - name: Push commits to a temp branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          branch: next-dev-cycle-${{ env.next_version }}

      - name: Create Pull Request to main branch
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          source_branch: next-dev-cycle-${{ env.next_version }}
          destination_branch: main
          pr_title: 'Start v${{ env.next_version }} development cycle'
